server:
  port: 15001

logging:
  level:
    org:
      restbucks: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_restbucks_tdd?useUnicode=true&characterEncoding=utf-8
    username: root
